# Generated by Django 3.2.3 on 2021-06-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomservice',
            old_name='name',
            new_name='service_name',
        ),
    ]
