# Generated by Django 3.2.3 on 2021-06-11 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_initial'),
        ('rooms', '0002_rename_name_roomservice_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservice',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commons.configchoice'),
        ),
    ]
