# Generated by Django 3.2.3 on 2021-06-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_initial'),
        ('rooms', '0003_alter_roomservice_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Service Title')),
                ('description', models.TextField(verbose_name='Service Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='roomservice',
            name='service_type',
        ),
        migrations.AddField(
            model_name='roomservice',
            name='service_type',
            field=models.ManyToManyField(to='commons.ConfigChoice'),
        ),
    ]
