# Generated by Django 3.2.3 on 2021-06-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210611_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservice',
            name='service_type',
            field=models.ManyToManyField(to='rooms.Service_spec'),
        ),
    ]
