# Generated by Django 3.2.3 on 2021-06-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_roomservice_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Room name must be unique', max_length=255, unique=True, verbose_name='Room Name'),
        ),
    ]
