# Generated by Django 3.2.3 on 2021-05-17 19:59

import autoslug.fields
import commons.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigChoiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and Unique', max_length=255, unique=True, verbose_name='Sub Category Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=commons.models.slugify, verbose_name='Sub Category Slug')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('entered_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='commons.configchoicecategory')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': ' Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='ConfigChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Required and Unique', max_length=255, unique=True, verbose_name='Category Name')),
                ('description', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=commons.models.slugify, verbose_name='Category Slug')),
                ('config_choice_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.configchoicecategory')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
