# Generated by Django 3.2.3 on 2021-06-10 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configchoicecategory',
            name='entered_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configchoicecategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='commons.configchoicecategory'),
        ),
        migrations.AddField(
            model_name='configchoice',
            name='config_choice_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.configchoicecategory'),
        ),
        migrations.AddField(
            model_name='configchoice',
            name='entered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.address'),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.company'),
        ),
    ]
