# Generated by Django 3.2.3 on 2021-06-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_auto_20210607_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
