# Generated by Django 3.2.3 on 2021-06-07 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20210524_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteladdress',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_address', to='hotels.hotel'),
        ),
    ]
